# ─────────────────────────────────────────────
# Auto-generate Ansible group_vars for the database.
# Every `tofu apply` refreshes DB credentials so Ansible
# can read them natively (no slurp+regex needed).
# Gitignored — never commit.
# ─────────────────────────────────────────────
resource "local_sensitive_file" "ansible_db_vars" {
  filename = "${path.module}/../ansible/group_vars/all/db_vars.yml"
  content  = <<-EOT
    ---
    # Auto-generated by OpenTofu. Do NOT commit.
    db_host: "${clevercloud_addon.database.configurations["MYSQL_ADDON_HOST"]}"
    db_port: "${clevercloud_addon.database.configurations["MYSQL_ADDON_PORT"]}"
    db_name: "${clevercloud_addon.database.configurations["MYSQL_ADDON_DB"]}"
    db_user: "${clevercloud_addon.database.configurations["MYSQL_ADDON_USER"]}"
    db_password: "${clevercloud_addon.database.configurations["MYSQL_ADDON_PASSWORD"]}"
  EOT

  file_permission = "0600"
}
